### ISSUE TITLE
Lexer Updates

### ISSUE THREAD

**Issue by tbreimer14** [UnionCompilerDesign/sicc#3]
### Details
Update the lexer with the latest changes to ensure better semantic ambiguity and allign with the C99 standard. 

### Issue Type
- [ ] Feature
- [ ] Bugfix
- [ ] Documentation
- [X] Refactoring
- [ ] Other:

**Comment by CalebLItalien** [comment]
See the PR for this issue. I'd like to bring in the rest of the lexer updates from core through this issue.
